# Trigger the build whenever `main` or `rel/*` is updated
trigger:
  - main
  - rel/*

# Disable PR trigger
pr: none

parameters:
  - name: PackageToPublish
    displayName: Package to Publish
    type: string
    values:
      - microsoft-vscode-azext-azureappservice
      - microsoft-vscode-azext-azureappsettings
      - microsoft-vscode-azext-azureauth
      - microsoft-vscode-azext-azureutils
      - microsoft-vscode-azext-dev
      - microsoft-eslint-config-azuretools
      - microsoft-vscode-azext-github
      - microsoft-vscode-azext-serviceconnector
      - microsoft-vscode-azext-utils
  - name: BranchToPublish
    displayName: Branch to Publish
    type: string
    default: "refs/heads/main"

# Scheduled nightly build of `main`
schedules:
  - cron: "0 0 * * *"
    displayName: Nightly scheduled build
    always: false # Don't rebuild if there haven't been changes
    branches:
      include:
        - main

# `resources` specifies the location of templates to pick up, use it to get AzExt templates
resources:
  repositories:
    - repository: azExtTemplates
      type: github
      name: microsoft/vscode-azuretools
      ref: main
      endpoint: GitHub-AzureTools # The service connection to use when accessing this repository

# Use those templates
extends:
  template: azure-pipelines/1esmain.yml@azExtTemplates
