trigger: none # Only run this pipeline when manually triggered

resources:
  pipelines:
    - pipeline: vscode-azurecontainerapps # identifier to use in pipeline resource variables
      source: \Azure Tools\VSCode\Extensions\vscode-azurecontainerapps # name of the pipeline that produces the artifacts
  repositories:
    - repository: azExtTemplates
      type: github
      name: microsoft/vscode-azuretools
      ref: alex/release-template
      endpoint: GitHub-AzureTools # The service connection to use when accessing this repository

variables:
  # Required by MicroBuild template
  - name: TeamName
    value: "Azure Tools for VS Code"

# Use those templates
extends:
  template: azure-pipelines/release-extension.yml@azExtTemplates
  parameters:
    pipelineID: $(resources.pipeline.vscode-azurecontainerapps.pipelineID)
    runID: $(resources.pipeline.vscode-azurecontainerapps.runID)
